public enum BuffType
{
    HEAL_HEALTH = 0,
    INCREASE_MAX_HEALTH = 1,
    INCREASE_BASE_DAMAGE = 2,
    BUFF_BASE_DAMAGE = 3,
    BUFF_UNLIMITED_STAMINA = 4,
    BUFF_INVINCIBILITY = 5,
    BUFF_MONEY_BONUS = 6,
    BUFF_EVASION_BOOST = 7,
    BUFF_CRIT_BOOST = 8,
    HEAL_STAMINA = 9
}